# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='college',
            name='users',
        ),
        migrations.AddField(
            model_name='user',
            name='colleges',
            field=models.ManyToManyField(to='api.College'),
        ),
    ]
