# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-14 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20160614_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='colleges',
            field=models.ManyToManyField(blank=True, to='api.College'),
        ),
    ]
